baseurl = "http://example.org/"
#languageCode = "en-us"
languageCode = "zh-client"
title = "Dataforcast  company"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Data ForCast "
	description = "focus on data collect ,data store,data extract "

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "DataForcast"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Data is everything"
		subtitle   = "We help Collect ,Store, Refine ,Extract, Analysis data "
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "We've got what you need!"
		description = "We are teams of senior IT engineer, Data Scientist ,Business insights Expert"
		buttonText  = "Get started!"


	# Service section
	[params.services]
		headline = "At your service"

        [[params.services.list]]
            icon = "fa-diamond"
            title = "Ready Data"
            description = "Our collected data for you may save your time"

        [[params.services.list]]
			icon = "fa-paper-plane"
			title = "Ready to Ship"
			description = "Our ready data analysis power is ready for your"

		[[params.services.list]]
            icon = "fa-newspaper-o"
            title = "Up to Date"
            description = "We keep  your data updated and managed"

        [[params.services.list]]
            icon = "fa-heart"
            title = "Made with Passion"
            description = "We take care of your data with love"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Take Action now  to Save your Time and Money"

		[params.aside.button]
			text = "Get Price Now"
			link = "https://github.com/boyzhujian/dataforcast.git"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "151-5018-0551"
		email = "610576334@qq.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
